# This docker-compose-pyver.yml extends the base docker-compose.yml
# to run three web services for different PYVER (3.11 and 3.13, 3.12 is the default)
# but they all use the same redis and postgres service.
# Run `docker compose -f docker-compose-workers.yml up` to start it up.
include:
    - docker-compose.yml

services:
  migrations-311:
    extends:
      service: migrations
    build:
      args:
        PYVER: "3.11"

  migrations-313:
    extends:
      service: migrations
    build:
      args:
        PYVER: "3.13"

  web-311:
    extends:
      service: web
    build:
      args:
        PYVER: "3.11"
    ports: !override
      - "5001:5000"
    depends_on: !override
      # !override is necessary to remove the original migrations from depends_on
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      migrations-311:
        condition: service_completed_successfully

  web-313:
    extends:
      service: web
    build:
      args:
        PYVER: "3.13"
    ports: !override
      - "5003:5000"
    depends_on: !override
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      migrations-313:
        condition: service_completed_successfully
