from enum import Enum


class IngestionStatus(str, Enum):
    QUEUED = "QUEUED"
    COPYING = "COPYING"
    COPIED = "COPIED"
    VALIDATING = "VALIDATING"
    VALIDATED = "VALIDATED"
    COMPLETED = "COMPLETED"

    COPY_FAILED = "COPY_FAILED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
